export default function Home() {
  return (
    <main style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', fontFamily: 'sans-serif', backgroundColor: '#f0f2f5' }}>
      <div style={{ textAlign: 'center' }}>
        <h1>🚀 Next.js Frontend Slot Ready</h1>
        <p>Replace the code in <code>frontend-service/src/app/page.js</code> with the code generated by your other LLM.</p>
        <p>The backend API is live at <code>/api/</code></p>
      </div>
    </main>
  )
}